# Formatting rules are implemented via the ktlint plugin. As ktlint does not allow exceptions to rules, respective rules
# need to be disabled completely.
ktlint:
  ClassSignature:
    active: false
  ImportOrdering:
    active: false

naming:
  InvalidPackageDeclaration:
    active: false
